project:
  type: website
  render:
    - index.qmd
    - data-qc.qmd
    - rotorua-qc-summary.qmd
    - metadata.qmd

website:
  title: "Lake Rotorua Data Product"
  favicon: assets/favicon.ico
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Data Summary"
        href: rotorua-qc-summary.qmd
      - text: "Metadata"
        href: metadata.qmd
      - text: "QA/QC"
        href: data-qc.qmd
      - text: "License"
        href: LICENSE.md
    right:
      - icon: github
        href: https://github.com/limnotrack/f_rotorua

format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: false
    favicon: assets/favicon.ico

execute:
  freeze: auto  # don't re-run everything
  cache: false  # save memory/disk
