name: Render Quarto when updated

on:
  push:
    paths:
      - 'data-qc.qmd'
      - '.github/workflows/render-quarto.yaml'
      - 'rotorua-qc-summary.qmd'
      - 'metadata.qmd'
      - '_quarto.yml'

jobs:
  render:
    runs-on: ubuntu-latest
    
    env:
      GH_PAT: ${{ secrets.GH_PAT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libgdal-dev \
            libproj-dev \
            libgeos-dev \
            libudunits2-dev \
            gdal-bin \
            proj-bin

      - name: Install R packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: always
          cache-version: 0

      - name: Render and publish to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions

      # Discard any uncommitted changes before switching branches
      - name: Clean working directory
        run: |
          git restore .
          git clean -fd
          
      # Step to reset the gh-pages branch to the latest commit
      - name: Clean up gh-pages branch history
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git reset --soft $(git commit-tree 'HEAD^{tree}' -m "Clean commit")
          git push origin gh-pages --force
